apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: grafana-pv
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}