apiVersion: v1
kind: PersistentVolume
metadata:
  name: "server-pv"
  labels:
    app: prometheus
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "monitor-local-storage"
  local:
    path: "/data/monitor/prometheus-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values: ["k8chvm6.data.int.dc1.ad.net"]