
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    {{- include "prometheus.alertmanager.labels" . | nindent 4 }}
  name: {{ template "prometheus.alertmanager.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
  accessModes:
{{ toYaml .Values.alertmanager.persistentVolume.accessModes | indent 4 }}
  storageClassName: "{{ .Values.alertmanager.persistentVolume.storageClass }}"

  resources:
    requests:
      storage: "{{ .Values.alertmanager.persistentVolume.size }}"

