
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.server.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
  accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 4 }}
  storageClassName: {{ .Values.server.persistentVolume.storageClass }}

  resources:
    requests:
      storage: {{ .Values.server.persistentVolume.size }}

